version: '3.7'

services:
  db:
    image: postgres:10.8
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build:
      context: ./frontend
      target: builder
    volumes:
      - frontend-dist:/frontend/build
    command: ["echo", "Successfully created static frontend files"] # No operation
  api:
    depends_on:
      - db
    build:
      context: .
    ports:
      - 8082:3000
    environment:
      LEIN_NO_DEV: "true"
volumes:
  frontend-dist:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/pitch-recorder-frontend-dist
