version: '3.7'

services:
  db:
    image: postgres:10.8
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    depends_on:
      - db
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
  frontend:
    depends_on:
      - api
    build:
      context: ./frontend
      target: base
    ports:
      - "3001:3000"
    command: ["yarn", "start"]
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 3002:8080
