version: '3.7'

services:
  db:
    image: postgres:10.8
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build:
      context: ./frontend
      target: base
    ports:
      - "3001:3000"
    command: ["yarn", "start"]
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/resources:/frontend/resources
      - ./frontend/public:/frontend/public
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 8080:8080
